### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by stela5** [Lixquid/atom-project-jump#1]
Sorry if this is obvious, but what is the keyboard shortcut for _Open_?  Right now I have to type `Ctrl+Shift+P > jump open [Enter] > foobar`

**Comment by Lixquid** [comment]
By default, I don't ship keyboard shortcuts with `project-jump`.

You can create your own by editing your `keymap.cson` and adding a shortcut to `project-jump:open`.

Here is an example:

``` coffee
"atom-text-editor:not([mini])":
  "ctrl-shift-alt-o": "project-jump:open"
```

With that keybinding, holding `ctrl`, `shift`, `alt`, and pressing `o` will open the Open Project dialog.

**Comment by stela5** [comment]
Worked like a charm.  Out of curiosity, why don't you include that as the default keyboard shortcut?

**Comment by Lixquid** [comment]
In previous versions of Atom, there was no way to disable a package from applying its keybindings without actually editing the package itself. This led to packages that implemented their own keybindings usually fighting each other for dominance when it came to respond to key sequences.

Quite a few developers decided that they'd rather just not ship keybindings, and allow for users themselves to define what keybindings they'd prefer themselves. Even now, I prefer to do that than try to force a particular keybinding set on users.

**Comment by stela5** [comment]
@Lixquid Ah, I see.  Thanks for the clarification.
